# Generated by Django 2.2.6 on 2021-01-16 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_study',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 15, 36, 20, 51268, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_study',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 15, 36, 20, 51230, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
