# Generated by Django 2.2.6 on 2021-01-17 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_study',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 13, 10, 55, 670842, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_study',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 13, 10, 55, 670805, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
