# Generated by Django 2.2.6 on 2021-01-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='info',
            name='bachelor',
        ),
        migrations.RemoveField(
            model_name='info',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='info',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='info',
            name='end_study',
        ),
        migrations.RemoveField(
            model_name='info',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='info',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='info',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='info',
            name='major',
        ),
        migrations.RemoveField(
            model_name='info',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='info',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='info',
            name='start_study',
        ),
        migrations.RemoveField(
            model_name='info',
            name='university',
        ),
    ]
